package com.accenture.hackathon.batch;

import java.util.Arrays;
import java.util.List;
import java.util.Map;

public class TestFeedbackBatch implements FeedbackBatch {
    @Override
    public List<String> getFeedback(Map<String, String> params) {
        return Arrays.asList("So for no reason other than the need to upgrade my 3 year old TV (Panasonic Viera TX-L37E5B) I purchased this TV. Delivery was swift and took 2 days. Setting up was quick, most impressed with the stand which whilst solid was child's play to set up. At the back there are only 2 HDMI slots, 1 Scart socket (Really???) An aerial socket , the usual line in ,line out sockets, A LAN Port, 1 USB port and a digital optical port. Set up was a breeze. (Kind of helps my last two tellies have been Panasonic) .\n" +
                "\n" +
                "Picture quality, I'll agree with a number of posters that the picture quality for terrestrial TV isn't as good as it could be and the picture quality comes across as soft. However on HD channels the quality is what you'd expect. However I must admit that my previous TV does produce a much better picture quality. Mind you it cost almost twice as much as this one.\n" +
                "Update 30/06/15\n" +
                "I've updated my BR player (SonyS5500) and wow, what can I say, yes I know its the BR, but the picture quality is absolutely fantastic.\n" +
                "\n" +
                "Not impressed with the TV guide, it is somewhat slower in coming up than the previous iteration , and seeing the cursor going round can be somewhat frustrating.(You can access the old type TV guide via the apps button)\n" +
                "\n" +
                "Soundwise, the TV is a big improvement from my other TVs.\n" +
                "\n" +
                "Internetwise, I purchased this TV in which to access Catch-up TV. However at the moment the service is somewhat limited and it isn't the full service I've seen with Virgin,Sky and You-View. But apparently Freeview-Play is just around the corner and this TV is already set up for it. As the TV is WiFi equipped, you already have apps for BBC i_Player, and other channel catch up. We watched the last 2 episodes of Jonathan Strange and Mr Norrell and they were a pleasure to watch.\n" +
                "\n" +
                "The remote is the same Panasonic design they have used for their TVs for the past few years, with just a few changes.\n" +
                "\n" +
                "Conclusion:\n" +
                "For the price this is a fantastic TV, yet for me, the picture quality for day to day to use, just doesn't cut it for me and it will be relocated to the spare room. Don't get me wrong, it is a good TV, however, I have become used to a much sharper TV, so I will be looking at the higher spec TV for our day to day viewing for our front room.",
                "This is a great second TV for us. Our main TV is a Panasonic too. No complaints at all with the TV. Very light weight to handle and easy to get set up.\n" +
                        "My complaint is with Panasonic themselves. As recommended I went online to register the product. Panasonic had an offer of 5 years free warranty at the time. I filled in the info and had to choose a retailer........does NOT apply to products bought from Amazon!!!!!! I was not happy and emailed Panasonic.....I needn't have bothered, they didn't care. The TV cost the same as anywhere else but it was more convenient for me to buy it from Amazon. I am still angry about it and still just have 1 year warranty. Either Amazon or Panasonic should make the playing field level for us. I don't blame Amazon...if they are even aware....but Panasonic has sold me its last product, however good they are.",
                "Wow I wasn't sure what to expect with this TV but it has really impressed both my husband and I with its functionality, design and picture quality. This TV was on trial to replace a Samsung of the same size (40\") that my husband purchased during his bachelor days. We had always been happy with that TV, worked perfectly, looked good and did the job.\n" +
                        "\n" +
                        "So on to the new TV. I unpacked, assembled and connected this TV myself. So the fact that *I* did this by myself without a hitch means this is super easy to set up. If you are like me, and nervous around new technology don't hold back with this one, it works like a dream. The TV itself is a lot thinner/slimmer and nicer looking than our current one even though they share the same screen size. I think this is due to the relatively slim/narrow bezel around the screen which to me, makes it seem like the screen itself is bigger than the 40\" it is. It also fits really neatly and unobtrusively into a small living room and doesn't contribute to making the room look smaller or overcrowded.\n" +
                        "\n" +
                        "The picture quality on this TV is superb - watching things like The Island with all the colours, the greens etc really makes for a wonderful viewing experience. We have also watched a number of blue ray DVDs and things like Avatar etc really come into their own on this screen. Another thing I have noticed is that 4OD looks much much crisper on this TV than our previous one which was always murky and slightly blurry.\n" +
                        "\n" +
                        "We mostly watch Netflix and 4OD and found these easy to set up and use. The quality has been excellent and we haven't experienced any issues in the 32/33 days that we have been using this. We have also used YouTube (although I prefer seeing those videos on a smaller device like an Ipad) and have found that easy to set up and access.\n" +
                        "\n" +
                        "My husband uses this screen for gaming - he has played The Last of Us, one of the new Resident Evils and some other war type game on it and seems to very much enjoy the experience as he's hardly come off it since.\n" +
                        "\n" +
                        "All in all, I would totally recommend this TV and if I were to repurchase this, I would go for the bigger screen size now I know how slim and attractive the actual unit is. We have successfully and easy linked it to the internet, Netflix, the PlayStation and used it to watch DVDs. We will be joining the Amazon Instant Film programme shortly so we can enjoy a wider variety of things to watch.\n" +
                        "\n" +
                        "In future, when it comes to replacing this TV, I would definitely look at another Panasonic over the brand we currently have. The difference in quality to me seems really quite considerable even though the screen size and some of the other specs are fairly similar. For example, both TVs are HD quality but the picture quality on the Panasonic is to me (and my husband and sister-in-law agreed) a lot better than our previous one. I am delighted with the item and would definitely recommend it to others based on my experience.",
                "OK, there is now so much choice out there when it comes to mid-range TV panels that even at this price point the TX40 is going to face stiff competition. Well my first thoughts here are that I am impressed, very impressed. I’ve always been a fan of Panasonic preferring their natural colours to similar priced Samsung, Pioneer alternatives and on first viewing this set does indeed seem to offer a lot for your money.\n" +
                        "\n" +
                        "Unpacking the TV immediately reveals just how much flat screen panel technology has advanced over the years - I was completely taken aback by just how light the unit was and was able to assemble the TV by myself within minutes (thanks to Panasonic for a very ergonomic & used friendly stand mechanism). Looks wise I would say that discrete rules the day, the panel is completely unobtrusive and looks as if it has been designed for wall mounting. The stand is good enough though and although made of plastic has a brushed metal appearance set against a black frame, it really is hard to believe this is 40” which a few years ago would have been considered large.\n" +
                        "\n" +
                        "In terms of spec again Panasonic have been generous. Firstly we have a 100HZ LED panel (50HZ just doesn’t cut the mustard these days) with adaptive backlight dimming to add “realism” to picture contrast. Despite its thinness (the panel is a mere 47mm wide) Panasonic have squeezed in 20W of amplification with added surround sound effects to increase the sound stage. Now this is never going to replace a sound bar or more advanced audio and I found the surround sound option to be mediocre, but on first listen, voices and even music had a depth and tonal quality that genuinely surprised me, not harsh on the ears at all and all very natural. The set also comes with analogue and optical digital audio outputs so upgrading the sound is easy.\n" +
                        "\n" +
                        "In terms of connectivity the Panasonic is also pretty much feature packed, I was able to connect to my home wi-fi first time allowing me to stream video, photos and music from my PC, or tablet via DLNA. I actually like Panasonics trade mark application-based browser, it is easy to select/amend home screens and switch application from the TV to say the shopping based functions, social media, SKYPE or catch-up TV. There is also a web browser, letting you surf the web. In all cases the response form the remote was very good, The TX40 comes with “flexible Freetime” meaning you can scroll back through TV listings and watch programmes from catch-up services such as BBC iPlayer, 4oD and Demand 5 without having to open specific applications. Freeview HD is standard meaning long as your aerial is digital all the main Freeview HD channels are there at your fingertips.\n" +
                        "\n" +
                        "So what about that all important picture quality? Well once again, straight out of the box I was surprised by the quality and “natural” warmth of the colours displayed on screen. The picture was razor sharp the brightness/contrast well balanced (if the latter slightly over emphasised) and on watching highlights of the grand prix the 100HZ panel showed no motion blur whatsoever. All in all quite impressive. The usual viewing presets are there (such as Cinema, Dynamic etc) all of which can be customized using both the basic and advanced editing options. I own the classic TX-P60ZT65B and it really is worthwhile taking time (and research) to fine tune the picture to optimum. Like most sets the standard viewing mode has the contrast set to 100% with the backlight also set to high. I would start off by reducing that contrast down to at least 50% and taking it from there. The advanced editing options include white balance, colour management and gamma, get these right (plenty of info on the net as to how) first and you really will see a difference. I will probably update the review once I have had a chance to do my own fine tuning.\n" +
                        "\n" +
                        "All in all coming in at just under £400 you are getting a lot of TV for your money here and with the lightness and simple ergonomics, for me this set would make for the perfect wall mounted bedroom companion or main TV in a flat or smaller front room. The interface is easy and intuitive, the remote a doddle to operate, there are picture editing options a plenty and in terms of features and connectivity Panasonic have really excelled. Most importantly the picture is natural with great depth of field. brightness and contrast and with a little editing within 10 minutes I was able improve upon the already good standard picture. Finally for a TV at this price point I found the standalone sound to be more than reasonable. A definite thumbs up then and worthy 5 stars for what should be a 2015 winner.");
    }
}
